#############################################################################
# Makefile for building: libConsole.1.0.0.dylib
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sun Feb 10 13:39:25 2013
# Project:  Console.pro
# Template: lib
# Command: /usr/local/bin/qmake -o Makefile Console.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DCONSOLE_LIBRARY -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.4/mkspecs/unsupported/macx-clang -I. -I/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/lib/QtScript.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/lib/QtScript.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.4/include -I-I/usr/local/opt/flex/include -I. -F/usr/local/Cellar/qt/4.8.4/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -single_module -dynamiclib -compatibility_version	1.0 -current_version	1.0.0 -install_name	libConsole.1.dylib
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.4/lib -L/usr/local/Cellar/qt/4.8.4/lib -L/usr/local/lib -lreadline.6.2 -lhistory.6.2 -L/usr/local/opt/flex/lib -lfl -framework QtScript -L/usr/local/Cellar/qt/4.8.4/lib -F/usr/local/Cellar/qt/4.8.4/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = console.cpp \
		commandinterpreter.cpp \
		filelogger.cpp \
		qsignalcatcher.cpp cmd.cpp \
		moc_console.cpp \
		moc_commandinterpreter.cpp \
		moc_filelogger.cpp \
		moc_qsignalcatcher.cpp
OBJECTS       = console.o \
		commandinterpreter.o \
		filelogger.o \
		qsignalcatcher.o \
		cmd.o \
		moc_console.o \
		moc_commandinterpreter.o \
		moc_filelogger.o \
		moc_qsignalcatcher.o
DIST          = /usr/local/Cellar/qt/4.8.4/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_pre.prf \
		flex.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/include_source_dir.prf \
		Console.pro
QMAKE_TARGET  = Console
DESTDIR       = 
TARGET        = libConsole.1.0.0.dylib
TARGETA       = libConsole.a
TARGETD       = libConsole.1.0.0.dylib
TARGET0       = libConsole.dylib
TARGET1       = libConsole.1.dylib
TARGET2       = libConsole.1.0.dylib

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET): cmd.cpp $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA): cmd.cpp $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
	$(RANLIB) $(TARGETA)

Makefile: Console.pro  /usr/local/Cellar/qt/4.8.4/mkspecs/unsupported/macx-clang/qmake.conf /usr/local/Cellar/qt/4.8.4/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_pre.prf \
		flex.pri \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.4/lib/QtScript.framework/QtScript.prl \
		/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Console.pro
/usr/local/Cellar/qt/4.8.4/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.4/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_pre.prf:
flex.pri:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.4/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.4/lib/QtScript.framework/QtScript.prl:
/usr/local/Cellar/qt/4.8.4/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Console.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Console1.0.0 || $(MKDIR) .tmp/Console1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Console1.0.0/ && $(COPY_FILE) --parents cmd.l .tmp/Console1.0.0/ && $(COPY_FILE) --parents console.h commandinterpreter.h filelogger.h qsignalcatcher.h Console_global.h helpers.h .tmp/Console1.0.0/ && $(COPY_FILE) --parents console.cpp commandinterpreter.cpp filelogger.cpp qsignalcatcher.cpp .tmp/Console1.0.0/ && (cd `dirname .tmp/Console1.0.0` && $(TAR) Console1.0.0.tar Console1.0.0 && $(COMPRESS) Console1.0.0.tar) && $(MOVE) `dirname .tmp/Console1.0.0`/Console1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Console1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_flex_make_all: cmd.cpp
compiler_flex_clean:
	-$(DEL_FILE) cmd.cpp
cmd.cpp: cmd.l
	flex -o cmd.cpp cmd.l

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_console.cpp moc_commandinterpreter.cpp moc_filelogger.cpp moc_qsignalcatcher.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_console.cpp moc_commandinterpreter.cpp moc_filelogger.cpp moc_qsignalcatcher.cpp
moc_console.cpp: commandinterpreter.h \
		filelogger.h \
		console.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ console.h -o moc_console.cpp

moc_commandinterpreter.cpp: filelogger.h \
		commandinterpreter.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ commandinterpreter.h -o moc_commandinterpreter.cpp

moc_filelogger.cpp: filelogger.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ filelogger.h -o moc_filelogger.cpp

moc_qsignalcatcher.cpp: qsignalcatcher.h
	/usr/local/Cellar/qt/4.8.4/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qsignalcatcher.h -o moc_qsignalcatcher.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_flex_clean compiler_moc_header_clean 

####### Compile

console.o: console.cpp console.h \
		commandinterpreter.h \
		filelogger.h \
		helpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o console.o console.cpp

commandinterpreter.o: commandinterpreter.cpp helpers.h \
		console.h \
		commandinterpreter.h \
		filelogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commandinterpreter.o commandinterpreter.cpp

filelogger.o: filelogger.cpp filelogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filelogger.o filelogger.cpp

qsignalcatcher.o: qsignalcatcher.cpp qsignalcatcher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qsignalcatcher.o qsignalcatcher.cpp

cmd.o: cmd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmd.o cmd.cpp

moc_console.o: moc_console.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_console.o moc_console.cpp

moc_commandinterpreter.o: moc_commandinterpreter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_commandinterpreter.o moc_commandinterpreter.cpp

moc_filelogger.o: moc_filelogger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filelogger.o moc_filelogger.cpp

moc_qsignalcatcher.o: moc_qsignalcatcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qsignalcatcher.o moc_qsignalcatcher.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

